name: 'quack-scan'
author: 'quack-scan'
description: 'Run static code dependency scan using Black Duck Synopsys scan for NPM and PIP. '
runs: 
  using: 'node12'
  main: '.github/workflows/quack-scan.yml'
branding:
  icon: 'box'  
  color: 'yellow'