name: PMD Source Code Analyzer

# Controls when the action will run. 
on:
  # Triggers the workflow on push events for the release or master branch
  # master branch is included because some repos still use that as the base branch.
  pull_request:
    branches: [ release, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pmd:
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
      - uses: actions/checkout@v2

    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd
        run: pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text
